# Copyright (c) 2018-2019 The Ion developers
name: ckti-ioncore-current
base: core18
version: 4.0.00
summary:   gaming related peer-to-peer network based digital currency
description: |
  Ion Core is an MIT licensed,  open source, gaming oriented,
  blockchain-based cryptocurrency with ultra fast transactions,
  low fees, high network decentralization, and Zero 
  Knowledge cryptography proofs for industry-leading transaction anonymity.
  
  This package includes following binaries:
  
    iond, ion-cli, ion-tx, ion-qt, test_ion, test_ion-qt
  
  Default homefolder:
  
    ~/snap/ioncore/common/.ioncoin
  
  How to launch snap binaries in terminal?:
  
    ioncore.qt     - launches Ion Core QT (ion-qt)
    ioncore.daemon - launches Ion Core daemon (iond)
    ioncore.cli    - launches Ion Core RPC (ion-cli)
    ioncore.tx     - launches Ion Core ion-tx utility (ion-tx)
    test           - launches test_ion
  
  Additional launchers for tegtest and testnet:
  
    ioncore.qt-testnet     - launches Ion Core QT with testnet=1
    ioncore.daemon-testnet - launches Ion Core daemon with testnet=1
    ioncore.cli-testnet    - launches Ion Core RPC with testnet=1
  
    ioncore.qt-regtest     - launches Ion Core QT with regtest=1
    ioncore.daemon-regtest - launches Ion Core daemon with regtest=1
    ioncore.cli-regtest    - launches Ion Core RPC with regtest=1
  
  Documentation and wiki:
  
  - Wiki (Ion Core):    https://github.com/ioncoincore/ion/wiki
  - Wiki (Ionomy):      https://github.com/ionomy/ion/wiki
  - Wiki (Ion Core CE): https://github.com/cevap/ion/wiki
  - Technical documentation: https://techdoc.ioncoin.org
  - Whitepaper: https://ionomy.com/en/whitepaper
  - Technical whitepaper: https://tinyurl.com/y3st8jfb
  
  Get source code from Github: https://github.com/ioncoincore/ion.git
  Get CE source code from Github: https://github.com/cevap/ion.git
  
  Chat with Support on Discord: https://discord.gg/vuZn7gC
  
  Contact us on social networks and forums:
  
  - Instagram: https://t.me/ionomy
  - Twitter:   https://twitter.com/ionomics
  - Reddit:    https://www.reddit.com/r/ionomy/
  - Facebook:  https://facebook.com/ionomy
  
  - Feature request: https://tinyurl.com/y5ds7s3t
  - I need help/support: https://tinyurl.com/yy6xa3p4
  - Report a bug: https://tinyurl.com/y5wzybwe
  - Report some random issue: https://tinyurl.com/y5cgm2vp
  - Testing Report: https://tinyurl.com/y39n2hsv

  Warning: Please do not use shady snapcraft's shady forum for questions
grade: stable
confinement: strict
icon: src/qt/res/src/ion.svg
apps:
  daemon:
    command: iond
    plugs: [network, network-bind, network-status, home, removable-media]
    desktop: iond.desktop
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  daemon-testnet:
    command: iond --testnet
    plugs: [network, network-bind, network-status, home, removable-media]
    desktop: iond_testnet.desktop
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  daemon-regtest:
    command: iond --regtest
    desktop: iond_regtest.desktop
    plugs: [network, network-bind, network-status, home, removable-media]
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  qt:
    command: ion-qt
    plugs: [network, network-bind, network-status, unity7, desktop, desktop-legacy, wayland, x11, mir, opengl, home, gsettings, removable-media, screen-inhibit-control, pulseaudio, media-hub]
    desktop: ion-qt.desktop
    environment:
      QT_XKB_CONFIG_ROOT: $SNAP_USER_DATA:$SNAP/usr/share:$QT_XKB_CONFIG_ROOT
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  qt-testnet:
    command: ion-qt --testnet
    plugs: [network, network-bind, network-status, unity7, desktop, desktop-legacy, wayland, x11, mir, opengl, home, gsettings, removable-media, screen-inhibit-control, pulseaudio, media-hub]
    desktop: ion-qt_testnet.desktop
    environment:
      QT_XKB_CONFIG_ROOT: $SNAP_USER_DATA:$SNAP/usr/share:$QT_XKB_CONFIG_ROOT
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  qt-regtest:
    command: ion-qt --regtest
    plugs: [network, network-bind, network-status, unity7, desktop, desktop-legacy, wayland, x11, mir, opengl, home, gsettings, removable-media, screen-inhibit-control, pulseaudio, media-hub]
    desktop: ion-qt_regtest.desktop
    environment:
      QT_XKB_CONFIG_ROOT: $SNAP_USER_DATA:$SNAP/usr/share:$QT_XKB_CONFIG_ROOT
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  cli:
    command: ion-cli
    plugs: [network, network-bind, network-status, home]
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  cli-testnet:
    command: ion-cli --testnet
    plugs: [network, network-bind, home]
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  cli-regtest:
    command: ion-cli --regtest
    plugs: [network, network-bind, home]
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  tx:
    command: ion-tx
    plugs: [home]
  test:
    command: test_ion
    plugs: [home]
parts:
  ion:
    source: .
    plugin: nil
    override-build: |
      echo "+++++++++++++++++++++++++++++++++++++++++++++++"
      if [ $SNAPCRAFT_ARCH_TRIPLET = "i386-linux-gnu" ]; then
        HOST="i686-linux-gnu"
      else
        HOST="${SNAPCRAFT_ARCH_TRIPLET}"
      fi
      if [ $HOST = "x86_64-linux-gnu" ]; then
        wget https://github.com/ioncoincore/ion/releases/download/v4.0.00/ion-4.0.0-x86_64-linux-gnu.tar.xz
        sha256sum=a5a937fa3ea64044598f178171f4512bced82f8d9fedfb92d591b71a7e16d7bc
        sha256sumdl=`sha256sum ion-4.0.0-x86_64-linux-gnu.tar.xz  | awk '{print $1}'`
        if [ $sha256sum != $sha256sumdl ] ; then
          echo "sha256sums do not match exiting build"
          exit 1
        fi
        tar -xf ion-4.0.0-x86_64-linux-gnu.tar.xz
        cp -p ion-4.0.0/bin/* $SNAPCRAFT_PART_INSTALL/usr/bin
        cp -p ion-4.0.0/share/man/man1/* $SNAPCRAFT_PART_INSTALL/usr/share/man/man1
        rm -rf ion-4.0.0*
        $SNAPCRAFT_PART_INSTALL/usr/lib/${HOST}/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders > $SNAPCRAFT_PART_INSTALL/usr/lib/${HOST}/gdk-pixbuf-2.0/2.10.0/loaders.cache
      elif [ $HOST = "i686-linux-gnu" ]; then
        wget https://github.com/ioncoincore/ion/releases/download/v4.0.00/ion-4.0.0-i686-pc-linux-gnu.tar.xz
        sha256sum=031e18867afe100e1ab6ea84adf5f01bdff22d0f35abc9dd8e1bdb68c64f8b24
        sha256sumdl=`sha256sum ion-4.0.0-i686-pc-linux-gnu.tar.xz  | awk '{print $1}'`
        if [ $sha256sum != $sha256sumdl ] ; then
          echo "sha256sums do not match exiting build"
          exit 1
        fi
        tar -xf ion-4.0.0-i686-pc-linux-gnu.tar.xz
        cp -p ion-4.0.0/bin/* $SNAPCRAFT_PART_INSTALL/usr/bin
        cp -p ion-4.0.0/share/man/man1/* $SNAPCRAFT_PART_INSTALL/usr/share/man/man1
        rm -rf ion-4.0.0*
        $SNAPCRAFT_PART_INSTALL/usr/lib/${HOST}/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders > $SNAPCRAFT_PART_INSTALL/usr/lib/${HOST}/gdk-pixbuf-2.0/2.10.0/loaders.cache
        $SNAPCRAFT_PART_INSTALL/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders > $SNAPCRAFT_PART_INSTALL/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/gdk-pixbuf-2.0/2.10.0/loaders.cache
      elif [ $HOST = "arm-linux-gnueabihf" ]; then
        wget https://github.com/ioncoincore/ion/releases/download/v4.0.00/ion-4.0.0-arm-linux-gnuebihf.tar.xz
        sha256sum=306cdc1a813ca19a968c997ad1bd50b644eac012162ea6f1a806d03c94c36066
        sha256sumdl=`sha256sum ion-4.0.0-i686-pc-linux-gnu.tar.xz  | awk '{print $1}'`
        if [ $sha256sum != $sha256sumdl ] ; then
          echo "sha256sums do not match exiting build"
          exit 1
        fi
        tar -xf ion-4.0.0-arm-linux-gnuabihf.tar.xz
        cp -p ion-4.0.0/bin/* $SNAPCRAFT_PART_INSTALL/usr/bin
        cp -p ion-4.0.0/share/man/man1/* $SNAPCRAFT_PART_INSTALL/usr/share/man/man1
        rm -rf ion-4.0.0*
        $SNAPCRAFT_PART_INSTALL/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders > $SNAPCRAFT_PART_INSTALL/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/gdk-pixbuf-2.0/2.10.0/loaders.cache
      elif [ $HOST = "aarch64-linux-gnu" ]; then
        wget https://github.com/ioncoincore/ion/releases/download/v4.0.00/ion-4.0.0-aarch64-linux-gnu.tar.xz
        sha256sum=a44278f5fc7e3720c4e3b095b7e3cb4df631c5953a309bc4c5a2947777950b56
        sha256sumdl=`sha256sum ion-4.0.0-i686-pc-linux-gnu.tar.xz  | awk '{print $1}'`
        if [ $sha256sum != $sha256sumdl ] ; then
          echo "sha256sums do not match exiting build"
          exit 1
        fi
        tar -xf ion-4.0.0-aarch-linux-gnu.tar.xz
        cp -p ion-4.0.0/bin/* $SNAPCRAFT_PART_INSTALL/usr/bin
        cp -p ion-4.0.0/share/man/man1/* $SNAPCRAFT_PART_INSTALL/usr/share/man/man1
        rm -rf ion-4.0.0*
        $SNAPCRAFT_PART_INSTALL/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders > $SNAPCRAFT_PART_INSTALL/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/gdk-pixbuf-2.0/2.10.0/loaders.cache
      else
        echo "${HOST} unsupported"
      fi

    build-packages:
      - curl
      - wget
      - gcc
      - gcc-8
      - g++
      - g++-8
      - make
      - autoconf
      - automake
      - cmake
      - pkg-config
      - libtool
      - bsdmainutils
      - binutils
      - python3
      - help2man
      - doxygen
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - locales-all
      - qtwayland5
      - ca-certificates
    after:
      - patches
  patches:
    source: snap/local/patches
    plugin: dump
    prime:
      - -*
  desktop:
    source: snap/local/desktop
    plugin: dump
